name: CI/CD PROD Ludo-mobile - BUILD

on:
  push:
    branches: [main]

jobs:
  build_web:
    name: build_web
    needs: [ release ]
    runs-on: ubuntu-latest
    steps:
      - name: Create .env file
          run: |
            echo "API_KEY=${{ secrets.API_KEY }}" >> assets/.env
            echo "API_ID=${{ secrets.API_ID }}" >> assets/.env
            echo "MESSAGING_SENDER_ID=${{ secrets.MESSAGING_SENDER_ID }}" >> assets/.env
            echo "PROJECT_ID=${{ secrets.PROJECT_ID }}" >> assets/.env
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.9"
      - run: flutter pub get
      - run: flutter pub run build_runner build
      - run: flutter test
      - run: flutter build web --dart-define=API_URL=http://api-ludosaure-load-balancer-2124171361.eu-west-1.elb.amazonaws.com

  build_apk:
    name: build_apk
    runs-on: ubuntu-latest
    steps:
      - name: Create .env file
          run: |
            echo "API_KEY=${{ secrets.API_KEY }}" >> assets/.env
            echo "API_ID=${{ secrets.API_ID }}" >> assets/.env
            echo "MESSAGING_SENDER_ID=${{ secrets.MESSAGING_SENDER_ID }}" >> assets/.env
            echo "PROJECT_ID=${{ secrets.PROJECT_ID }}" >> assets/.env
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.9'
      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'upload-keystore.jks'
          encodedString: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
      - run: flutter pub get
      - run: flutter pub run build_runner build
      - run: flutter test
      - run: flutter build apk --release --split-per-abi
      - run: flutter build appbundle --dart-define=API_URL=http://api-ludosaure-load-balancer-2124171361.eu-west-1.elb.amazonaws.com
      - name: Upload app bundle
        uses: actions/upload-artifact@v3
        with:
          name: appbundle
          path: build/app/outputs/bundle/release/app-release.aab

  release:
    name: Release app to production track
    needs: [ build_apk ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get appbundle from artifacts
        uses: actions/download-artifact@v3
        with:
          name: appbundle
      - name: Release app to internal track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAYSTORE_ACCOUNT_KEY }}
          packageName: com.ludosaure.ludo_mobile
          releaseFiles: app-release.aab
          track: production
          whatsNewDirectory: android/release-notes/
          status: completed

#  build_ios:
#    name: build_ios
#    needs: [ release ]
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: subosito/flutter-action@v2
#        with:
#          flutter-version: '3.3.9'
#          architecture: x64
#      - run: flutter pub get
#      - run: flutter pub run build_runner build
#      - run: flutter test
#      - run: flutter build ios --release --no-codesign --dart-define=API_URL=http://api-ludosaure-load-balancer-2124171361.eu-west-1.elb.amazonaws.com
